/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Fraccionario;
import clase.numeromixto;
import javax.swing.JOptionPane;

/**
 *
 * @author adalberto
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdMixto.setEnabled(false);
        cmdLimpiar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtNumerador2 = new javax.swing.JTextField();
        txtDenominador2 = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<>();
        txtNumerador1 = new javax.swing.JTextField();
        txtDenominador1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumerador3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtDenominador3 = new javax.swing.JTextField();
        txtResultadoNuMixto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtResultadoDeMixto = new javax.swing.JTextField();
        txtNumeroMixto = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdMixto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 60, 10));

        txtNumerador2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNumerador2.setForeground(new java.awt.Color(102, 0, 0));
        txtNumerador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerador2ActionPerformed(evt);
            }
        });
        txtNumerador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador2KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 60, -1));

        txtDenominador2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDenominador2.setForeground(new java.awt.Color(102, 0, 0));
        txtDenominador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador2KeyTyped(evt);
            }
        });
        jPanel1.add(txtDenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, -1));

        cmbOperacion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División" }));
        cmbOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, -1));

        txtNumerador1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNumerador1.setForeground(new java.awt.Color(102, 0, 0));
        txtNumerador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador1KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, -1));

        txtDenominador1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDenominador1.setForeground(new java.awt.Color(102, 0, 0));
        txtDenominador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador1KeyTyped(evt);
            }
        });
        jPanel1.add(txtDenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, -1));

        jLabel2.setText("operacionesconfraccionario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 160, 30));

        txtNumerador3.setEditable(false);
        jPanel1.add(txtNumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 80, 30));

        jLabel3.setText("=");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 20, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, -1));

        txtDenominador3.setEditable(false);
        jPanel1.add(txtDenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 80, 30));

        txtResultadoNuMixto.setEditable(false);
        jPanel1.add(txtResultadoNuMixto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 80, 30));

        jLabel4.setText("=");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 20, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 80, -1));

        txtResultadoDeMixto.setEditable(false);
        jPanel1.add(txtResultadoDeMixto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 80, 30));

        txtNumeroMixto.setEditable(false);
        jPanel1.add(txtNumeroMixto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 60, 40));

        cmdCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 120, -1));

        cmdLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        cmdMixto.setText("Converti a numero mixto");
        cmdMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMixtoActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMixto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(705, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumerador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerador2ActionPerformed

    private void txtNumerador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador2KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumerador2KeyTyped

    private void txtDenominador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador2KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDenominador2KeyTyped

    private void cmbOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperacionActionPerformed

    private void txtNumerador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador1KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumerador1KeyTyped

    private void txtDenominador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador1KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDenominador1KeyTyped

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int op,op2,num1,num2,den1,den2,mixto1 = 0,mixto2 = 0;
        Fraccionario f1,f2,f3,f = null;

        if (txtNumerador1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite el numerador en la primera fracción", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumerador1.requestFocusInWindow();

        }else if (txtNumerador2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite el numerador en la segunda fracción", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumerador2.requestFocusInWindow();

        }else if (txtDenominador1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite el denominador en la primera fracción", "Error", JOptionPane.ERROR_MESSAGE);
            txtDenominador1.requestFocusInWindow();
        }else if (txtDenominador2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite el denominador en la segunda fracción", "Error", JOptionPane.ERROR_MESSAGE);
            txtDenominador2.requestFocusInWindow();
        }else{

            op=cmbOperacion.getSelectedIndex();
            op2=cmbOperacion.getSelectedIndex();
            num1=Integer.parseInt(txtNumerador1.getText());
            num2=Integer.parseInt(txtNumerador2.getText());
            den1=Integer.parseInt(txtDenominador1.getText());
            den2=Integer.parseInt(txtDenominador2.getText());

            f1=new Fraccionario(num1,den1,mixto1);
            f2=new Fraccionario(num2,den2,mixto2);

            switch(op){
                case 0:
                f=f1.Sumar(f2);
                txtNumerador3.setText(""+f.getNumerador());
                txtDenominador3.setText(""+f.getDenominador());
                break;

                case 1:
                f=f1.Restar(f2);
                txtNumerador3.setText(""+f.getNumerador());
                txtDenominador3.setText(""+f.getDenominador());
                break;

                case 2:
                f=f1.Multiplicar(f2);
                txtNumerador3.setText(""+f.getNumerador());
                txtDenominador3.setText(""+f.getDenominador());
                break;

                case 3:
                f=f1.Dividir(f2);
                txtNumerador3.setText(""+f.getNumerador());
                txtDenominador3.setText(""+f.getDenominador());
                break;
            }
            cmdCalcular.setEnabled(false);
            cmdMixto.setEnabled(true);
            cmdLimpiar.setEnabled(true);
            cmdSalir.setEnabled(false);
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtNumerador3.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtDenominador3.setText("");
        txtNumeroMixto.setText("");
        txtResultadoNuMixto.setText("");
        txtResultadoDeMixto.setText("");
        cmbOperacion.setSelectedIndex(0);
        
        txtNumerador1.requestFocusInWindow();
        cmdCalcular.setEnabled(true);
            cmdMixto.setEnabled(false);
            cmdLimpiar.setEnabled(true);
            cmdSalir.setEnabled(true);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMixtoActionPerformed
        numeromixto r1,r2,r3 = null;
        int ent,nu,de;
        nu = Integer.parseInt(txtNumerador3.getText());
        de = Integer.parseInt(txtDenominador3.getText());
        ent = nu / de ;

        r1 = new numeromixto(nu,de, ent);
        r3= r1.Numeromixto();
        txtNumeroMixto.setText(""+r3.getDenominador());
        txtResultadoNuMixto.setText(""+r3.getNumerador());
        txtResultadoDeMixto.setText(""+r3.getEntera());

        cmdCalcular.setEnabled(false);
        cmdLimpiar.setEnabled(true);
        cmdMixto.setEnabled(false);
        cmdSalir.setEnabled(true);
    }//GEN-LAST:event_cmdMixtoActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMixto;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominador3;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumerador3;
    private javax.swing.JTextField txtNumeroMixto;
    private javax.swing.JTextField txtResultadoDeMixto;
    private javax.swing.JTextField txtResultadoNuMixto;
    // End of variables declaration//GEN-END:variables
}
